export type KeyConfig =
  'NODE_ENV' |
  'DB_HOST' |
  'DB_PORT' |
  'DB_NAME' |
  'DB_USERNAME' |
  'DB_PASS' |
  'TOKEN' |
  'BINANCE_API_KEY' |
  'BINANCE_API_SECRET' |
  'LIMIT_USDT' |
  'FUTURE_LEVERAGE' |
  'LINE_CHANNEL_SECRET' |
  'LINE_CHANNEL_ACCESS_TOKEN' |
  'LINE_GROUP_ID' |
  'LINE_USER_ID';
